### ISSUE TITLE
Receiving HTTP Error 403: Forbidden using DMAX Link

### ISSUE THREAD

**Issue by hrueppert** [Brawl345/Get-DMAX-Links#11]
Hi there,

first of all, i'm not sure, if this some to fix on this side of the script.

The script sucessfully created an excel sheet with all download links, for example "Roter Stahl - Der Panzer Clan".
When i try to download via youtube-dl i get a http error 403: Forbidden.

I'm using the newest version of this script and of yt-download. The Github of YT-DL only says, maybe the Download is not wanted anymore. 

Is there any solution, maybe by modif this script to get pass this?

Error Message:
youtube-dl.exe "https://dplaynordics-vod-06.akamaized.net/dplaydni/94222/0/hls/9064573004/playlist.m3u8?hdnts=st=1618338366~exp=1618424766~acl=/dplaydni/94222/0/hls/9064573004/*~hmac=08d1edfdfdf98c3d3266884a39cf8cc099e4aa98129ee33e8c229d270770e5ea" -o "Roter Stahl - Der Panzer-Clan - S01E06 - Abgetaucht!.mp4"
[generic] *~hmac=08d1edfdfdf98c3d3266884a39cf8cc099e4aa98129ee33e8c229d270770e5ea: Requesting header
WARNING: Could not send HEAD request to https://dplaynordics-vod-06.akamaized.net/dplaydni/94222/0/hls/9064573004/playlist.m3u8?hdnts=st=1618338366~exp=1618424766~acl=/dplaydni/94222/0/hls/9064573004/*~hmac=08d1edfdfdf98c3d3266884a39cf8cc099e4aa98129ee33e8c229d270770e5ea: HTTP Error 403: Forbidden
[generic] *~hmac=08d1edfdfdf98c3d3266884a39cf8cc099e4aa98129ee33e8c229d270770e5ea: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by Brawl345** [comment]
Just tried this with:
``` 
python dmax.py 7936
```
And I downloaded the episode you said and it works here. Did you start the download asap or did you wait a few hours? The download links expire after a few hours AFAIK.

Can you try again please? Make sure to download the download immediately and you can also use HLS Player addon for Chrome/Firefox to click the links and they should play in the browser. Or maybe it was just a server error on DMAX' part.

**Comment by hrueppert** [comment]
ok, i tried it and your right. Everything is fine.

As i tried it the first time, i only hat ASSET IDs in the Souce Code, no SHOW IDs. It try to find a series only with asset ids to proof my theory, but i didn't find anyone anymore.

It seems they are using only show ids at the moment. 

So thank you for your quick help, Problem is solved :-D
