### ISSUE TITLE
Epidsodenname fehlt nun im "Command"-String.

### ISSUE THREAD

**Issue by Maysi2k** [Brawl345/Get-DMAX-Links#14]
Servus!
Also die neue Version ist ja echt mega schnell, good Job!

Allerdings fehlt in der erstellten Tabelle nun bei mir der Episodennamen im "Command"-Befehl.

`youtube-dl...-o "Serie - S11E09.mp4"`  

Also das hinter der "S11E09" z.B. "Neues freies Land" fehlt.

Danke dir und VG,

**Comment by Brawl345** [comment]
Uups, danke, ist gefixt! Neues Release lad ich sofort hoch.

**Comment by Maysi2k** [comment]
Danke dir! :)
