### ISSUE TITLE
No longer working

### ISSUE THREAD

**Issue by Reiner1210** [Brawl345/Get-DMAX-Links#16]
No longer working for dmax.de

**Comment by Brawl345** [comment]
Can you give a show where it's not working? I've just tried it with an ID from this list: https://gist.github.com/Akamaru/3646c47b68cccead419716f3c4a7e86e and it works for me. DMAX seems to have a new design though so no idea how to find the showId now (haven't looked into it yet)

**Comment by Reiner1210** [comment]
Ok. I use 
https://github.com/Brawl345/Get-DMAX-Links/blob/master/README.md
and there the lookup for showid does no longer work. I assumed this this is also based to this project.
Where do you get the showid ???

**Comment by Reiner1210** [comment]
Is there a possibility to write plain txt (csv) files instead of the xls ?

**Comment by Reiner1210** [comment]
Ok. It works if we have the showid list. How is the list created ?

**Comment by Brawl345** [comment]
> Is there a possibility to write plain txt (csv) files instead of the xls ?

No, because I need an Excel sheet. You have to modify the program yourself.

> Ok. It works if we have the showid list. How is the list created ?

Good question, the list was created by @Akamaru. I think he just bruteforced the IDs. I don't know if it's still updated though, keeping up with DMAX is annoying.

**Comment by Brawl345** [comment]
You can also use youtube-dl or yt-dlp to directly download the episodes via an episode link so no need to use this tool anymore. For example: https://dmax.de/sendungen/112-feuerwehr-im-einsatz/videos -> https://dmax.de/sendungen/112-feuerwehr-im-einsatz/rettung-vom-kirchendach
