### ISSUE TITLE
No ShowID

### ISSUE THREAD

**Issue by heinrichhalle99** [Brawl345/Get-DMAX-Links#18]
Hi,

thank you for the tool. 
It appears to me that the websites code has changed - I cant find the showid any longer. Or is it only on my end?

Cheers

**Comment by Brawl345** [comment]
Yes, it has changed. I haven't had the time to look into where the ID is now. But you can also directly download episodes with youtube-dl or yt-dlp without this tool.

**Comment by heinrichhalle99** [comment]
Thanks for the quick reply! I was testing youtube-dl, but by simply using the show https link I am recieving an unsupported URL error. Or is there some better way?

**Comment by Brawl345** [comment]
It only works with episodes. You need to click on "Alle Videos zur Sendung" and then copy the links from there.

**Comment by Maysi2k** [comment]
Die einzelnen Episoden heißen dann in etwa so:

`https://d**x.de/sendungen/steel-buddies/panzer-alarm-im-westerwald`

Hab mal etwas mit den Entwicklertools geschaut, habe aber bisher keine ShowID gesichtet (heißt ggf. nun auch anders, hatte hits mit einer alten showid, die nun 'dmaxde_xxxx' hieß). Aber auch nur einmal...

Die alten ShowIDs gehen aber wohl weiterhin.
ggf. mal bei Git-User 'Akamaru' vorbei schauen ;)


VG,

**Comment by einfachruschi** [comment]
I no longer saved the ShowIDs.
I couldn't find anything in the source code under 'dmaxde_xxxx', where exactly is this entry? Is there already a solution here?

**Comment by heinrichhalle99** [comment]
Hmm, I still recieve error "ERROR: Unable to download JSON metadata: HTTP Error 404: Not found (caused by <HTTPError 404: 'Not Found'>)
I will just stream it :) Thanks anyways!

**Comment by hrueppert** [comment]
It seems that they are use the asset ID again.

Maybe it is possible to import this function from the python branch into the actual branch.

@heinrichhalle99 as workaround use the python branch here. That version will still download the episodes

**Comment by Brawl345** [comment]
You can find all show ids here:

* DMAX: https://de-api.loma-cms.com/feloma/page/sendungen/?environment=dmax&v=2
* TLC: https://de-api.loma-cms.com/feloma/page/sendungen/?environment=tlc&v=2
* HGTV: https://de-api.loma-cms.com/feloma/page/sendungen/?environment=hgtv&v=2

Found it while going to "Sendungen" on DMAX.DE - they load the whole show list as JSON over JavaScript. You can find every show with their show Id there.
