### ISSUE TITLE
List with show id

### ISSUE THREAD

**Issue by Reiner1210** [Brawl345/Get-DMAX-Links#19]
I founded a list of show ids for dmax. I have added some entries. @Brawl345 Do you want the update ?

**Comment by Brawl345** [comment]
Sure you can post it here

**Comment by Reiner1210** [comment]
<code>
5984: Alaskan Bush People
6000: Asphalt-Cowboys
6001: Das Survival-Duo
6003: Die Aquarium-Profis
6004: Fang des Lebens - Der gefährlichste Job Alaskas
6005: Diesel Brothers
6006: Die Wracktaucher
6007: Die Raritäten-Jäger
6008: Carspotting
6009: Moonshiners
6010: Wild Cuisine
6011: Yukon Men
6013: Die Baumhaus-Profis
6014: Naked Survival XXL
6016: Fast N' Loud
6017: Carinis Classic Cars
6018: Goldrausch in Alaska
6021: Fast N' Loud Crash-Clips
6023: Steel Buddies
6025: Die Gebrauchtwagen-Profis
6028: Border Control
6029: Deadly Jobs
6030: Die Monster-Jäger
6067: Full Pull
6073: Mega Shippers
6132: DMAX DOKU
6133: Ed Stafford: Allein gegen die Wildnis
6134: Die Goldsucher vom Devil's Canyon
6161: Der Geiger
6193: Goldrausch in Australien
6234: 112: Feuerwehr im Einsatz
6254: Auf eigene Gefahr!
6310: Naked Survival
6311: Der Feind in meinem Körper
6356: Hardcore Pawn
6367: Miami Custom Cars
6419: Survive! Mit Joe Vogel
6432: Tödliche See vor Oregon
6500: Home Rescue
6536: Gear Dogs
6629: Coopers Geheimnis
6690: Goldtaucher der Beringsee
6697: Australian Gold
6728: Mysterien von oben
6729: Will Castro
6735: Inside West Coast Customs
6757: Car Rescue
6865: UFOs
6883: American Chopper
6914: Parkers Klondike-Abenteuer
6922: Goldrausch am Yukon
6932: A2 - Abenteuer Autobahn
6934: Asphalt-Cowboys: Polen
6968: Lone Star Law
6979: Twin Turbos
7163: Outback Opal Hunters -  Edelsteinjagd in Australien
7345: Garage Rehab - Die Werkstatt-Retter
7402: Die Stubers
7501: Baggage Battles
7625: Parkers Dschungel-Abenteuer
7632: Der Pool-Profi
7634: Body Cam Cops
7761: Redwood Kings
7862: SOS Sydney - Einsatz vor der Küste
7874: Poschs Criminalz
7927: Goblin Works Garage
7936: Roter Stahl - Der Panzer-Clan
8012: Die Modellbauer - Das Duell
8409: Speed Is The New Black
8440: Die Schatzsucher von Snake Island
8554: Texas Custom Cars
8635: Die Beckenbauer
8653: Männer(t)räume
8699: Shifting Gears mit Aaron Kaufman
8752: Escobar: Die Jagd nach den Millionen
8827: Männer der See
8873: Chris & Mäx: Die Oldtimer-Spezialisten
8919: Die Abholzer
9069: Spurlos verschwunden - Ungelöste Mysterien mit Miroslav Nemec
9172: Nordalaska - Überleben am Polarkreis
9272: Die Auto-Messies
9284: Die Ludolfs - 4 Brüder auf'm Schrottplatz
9292: Helden der Lüfte
9505: Goldrausch in Südamerika
9506: Der Checker - Viel Auto, wenig Geld
9578: Wingmen - Zwei Brüder heben ab
9652: Expedition Unknown - Mythen auf der Spur
9653: Ed Stafford: Das Survival-Duell
9654: Hellfire Heroes - Einsatz in Kanada
9666: Las Vegas Hot Rods
9676: Worst-Case Scenario - Überleben mit Bear Grylls
9692: Marquards Ess-Klasse
9710: Supermaschinen
9727: Goldrausch: White Water Alaska
9801: Man vs. Food mit Casey Webb
9802: Ed Stafford - Wie ich die Welt überlebte
9824: Overhaulin' - Aufgemotzt und Abgefahrn
9830: Tuning-Alarm! Jo motzt auf
9856: Dein bestes Stück - Gebracht, gemacht
9884: Ed Stafford: Survival-Trip ins Ungewisse
9944: Highway Patrol
9945: Die Blockhaus-Profis
10027: Die Abräumer - Antiquitäten & Moneten
10037: Bad Chad Customs
10256: Jack Maxwell: Hochprozentig um die Welt
10275: A8 - Abenteuer Autobahn
10565: Trans Am - Zwei Brüder mit Drive
10703: Ivan & Zoran - Die Balkan-Car-Connection
10731: Roadkill - Krasse Karren
10732: Dark Waters mit Jeremy Wade
10733: Fish or Die - Angeltrip ins Ungewisse
11028: Head 2 Head - Stiftung Wagentest
11108: Youngtimer Duell
11109: Hot Rod Garage
11113: Building Alaska - Hausbau extrem
11329: Caravaning & Cooking: Brian auf großer Tour
11475: Savage Builds - Adams krasse Konstruktionen
11549: Euro Truckers - Immer auf Achse
11550: Goldrausch: Parkers Neuguinea-Abenteuer
11612: Goldrausch: Dave Turin’s Lost Mine
11713: Die Austausch-Cops: Einsatz im Ausland
11817: Barrett Jackson - Autos unterm Hammer
11945: Deutschland 24/7 - Ohne uns läuft nichts!
11991: Die Angelbuddies - Fischen weltweit
12014: Helden der Baustelle
12015: Cash für Chrom
12016: Dead of Winter
12089: Jägerleben
12108: Dead of Night
12131: Toy Hunter - Der Spielzeugjäger
12249: Body Cam 911 - Polizeieinsatz hautnah
12301: Dirty Mudder Truckers - Offroad Extrem
12353: Undercover Billionaire
12505: Die 80er: Ein mörderisches Jahrzehnt
12520: Outback Truckers
12732: Bronx Detective - Die Fälle des Ralph Friedman
12830: Ausgerechnet Sibirien: Ulf steigt aus
12945: Sidneys Welt
12946: World’s Deadliest - Um Haaresbreite
12955: Farmer Forever
13081: Expedition Unkown: Das Leben nach dem Tod
13319: SOS: Anleitung zum Überleben
13396: Chickens Bike Farm
13466: Steel Buddies: Sonderschicht XXL
13479: Barbecue Kings - Grillen um die Welt
13480: Abenteuer Autobahn: Brennpunkte
13767: Richard Hammond's BIG - Größer geht's nicht!
14252: Asphalt-Cowboys - Ladies on tour
14343: Die Gebrauchtwagen-Profis: Der Traumauto-Deal
14587: BBQ Battle - Die Grillmeister
14601: King of Trucks
15101: Aaron Kaufman: Der Extrem-Praktikant
15111: Border Control: Europas Grenzschützer
15186: Der Germinator - Ein deutscher Cop in Texas
15376: Shark Week auf DMAX
15404: Goldrausch: Parkers Australien-Abenteuer
15412: Die Pythonjäger - Einsatz in den Everglades
15452: Rohr frei! - Das Kanalkommando
15791: Moonshiners: Master Distiller
15792: Die Modellbauer - The Next Generation
15852: Helicopter ER – Rettung aus der Luft
16326: Die Modellbauer - Das Miniatur Wunderland
16762: Ed Stafford: Survival-Duell in China
16797: Car Kings
16837: Steel Buddies: Specials
17003: 100 Days Wild - Das Survival-Abenteuer
17445: Kawumm! - Die explosive Science-Show
17446: Salvage Squad - Die Bergungs-Profis
17879: Hammerfrauen
18087: Cal Fire - Feueralarm in Kalifornien
18090: Eiskaltes Gold
18091: Der Camping Clan - Alles für den Platz
18257: REVolution - Meilensteine der Auto-Entwicklung
18258: Salvage Kings - Demolieren und kassieren
18476: Fang des Lebens: Bloodline
18515: Crocodile Gold - Schatzsuche am Ende der Welt
18645: Naked Survival Solo - Allein in die Wildnis
18662: Blind Frog Ranch - Die Schatzsucher von Utah
19040: Expedition X - Dem Unheimlichen auf der Spur
19309: Scrap Kings - Alles Schrott!
19362: Undercover Billionaire: Zwischen Pleite und Profit

</code>

**Comment by BobCelso** [comment]
@Reiner1210 great work !

**Comment by Brawl345** [comment]
See the README, I added new instructions

**Comment by Reiner1210** [comment]
@Brawl345 Thank you ! - Do you know how the API is implemented ?
Here the list from the API

5984: Alaskan Bush People
6000: Asphalt-Cowboys
6001: Das Survival-Duo
6003: Die Aquarium-Profis
6004: Fang des Lebens
6005: Diesel Brothers
6007: Die Raritäten-Jäger
6009: Moonshiners
6011: Yukon Men
6013: Die Baumhaus-Profis
6014: Naked Survival XXL
6018: Goldrausch in Alaska
6023: Steel Buddies
6025: Die Gebrauchtwagen-Profis
6030: Die Monster-Jäger - Bestien auf der Spur
6073: Mega Shippers
6133: Ed Stafford: Allein gegen die Wildnis
6161: Der Geiger
6193: Goldrausch in Australien
6234: 112: Feuerwehr im Einsatz
6310: Naked Survival
6311: Der Feind in meinem Körper
6432: Fang des Lebens: Tödliche See vor Oregon
6500: Home Rescue
6690: Die Schatzsucher - Goldtaucher der Beringsee
6697: Australian Gold
6757: Car Rescue - Ran an den Rost!
6883: American Chopper
6932: A2 - Abenteuer Autobahn
6934: Asphalt-Cowboys: Polen
6961: Fluss-Monster
6968: Lone Star Law - Die Gesetzeshüter von Texas
7163: Outback Opal Hunters
7625: Parkers Dschungel-Abenteuer
7927: Goblin Works Garage
8012: Die Modellbauer - Das Duell
8440: Die Schatzsucher von Snake Island
8554: Texas Custom Cars
8635: Die Beckenbauer
8827: Männer der See
8873: Chris & Mäx: Die Oldtimer-Spezialisten
9292: Helden der Lüfte
9398: Steel Buddies: Die Auktion
9652: Expedition Unknown - Mythen auf der Spur
9653: Ed Stafford: Das Survival-Duell
9654: Hellfire Heroes - Einsatz in Kanada
9710: Supermaschinen
9802: Ed Stafford - Wie ich die Welt überlebte
9824: Overhaulin' - Aufgemotzt und Abgefahrn
9884: Ed Stafford: Survival-Trip ins Ungewisse
9945: Die Blockhaus-Profis
9948: Ed Stafford - Das nackte Überleben
10037: Bad Chad Customs
10275: A8 - Abenteuer Autobahn
10565: Trans Am - Zwei Brüder mit Drive
11113: Building Alaska - Hausbau extrem
11329: Caravaning & Cooking: Brian auf großer Tour
11475: Savage Builds - Adams krasse Konstruktionen
11549: Euro Truckers - Immer auf Achse
11550: Goldrausch: Parkers Neuguinea-Abenteuer
11612: Goldrausch: Dave Turin’s Lost Mine
11713: Die Austausch-Cops: Einsatz im Ausland
11945: Deutschland 24/7 - Ohne uns läuft nichts!
12014: Helden der Baustelle
12015: Cash für Chrom
12249: Body Cam 911 - Polizeieinsatz hautnah
12520: Outback Truckers
13081: Expedition Unkown: Das Leben nach dem Tod
13479: Barbecue Kings - Grillen um die Welt
13480: Abenteuer Autobahn: Brennpunkte
13767: Richard Hammond's BIG - Größer geht's nicht!
14252: Asphalt-Cowboys - Ladies on tour
14343: Die Gebrauchtwagen-Profis: Der Traumauto-Deal
14587: BBQ Battle - Die Grillmeister
14601: King of Trucks
15156: Die Monster-Jäger von Alaska
15186: Der Germinator - Ein deutscher Cop in Texas
15404: Goldrausch: Parkers Australien-Abenteuer
15412: Die Pythonjäger - Einsatz in den Everglades
15791: Moonshiners: Master Distiller
15792: Die Modellbauer - The Next Generation
16326: Die Modellbauer - Das Miniatur Wunderland
16762: Ed Stafford: Survival-Duell in China
17446: Salvage Squad - Die Bergungs-Profis
18090: Eiskaltes Gold
18091: Der Camping Clan - Alles für den Platz
18258: Salvage Kings - Demolieren und kassieren
18515: Crocodile Gold - Schatzsuche am Ende der Welt
18645: Naked Survival Solo - Allein in die Wildnis
18662: Blind Frog Ranch - Die Schatzsucher von Utah
19040: Expedition X - Dem Unheimlichen auf der Spur
19362: Undercover Billionaire
36063: Mud Mountain Truckers
36141: Wild Idaho - Die Aussteiger vom Salmon River
36197: Sydney Central Station - Leben für die Schiene
36360: Rust Valley Restorers
37839: Goldrausch: Winter's Fortune
38944: Heinz im Glück - Goldene Geschäfte
39813: The Earthshot Prize: Repairing Our Planet
39966: Expedition: Zurück in die Zukunft
43291: Louisiana Law - Die Wildlife-Ranger
43661: Helden des Handwerks
46134: Richard Hammond's Car Workshop
47420: Helden des Hafens
47500: In Seenot - Einsatz an der Küste
47697: BBQ Street
49774: Helden der See
49776: Goldrausch: Einsatz für Freddy Dodge
51538: Camper-Träume - Wohnen auf vier Rädern
52930: Goldrausch: Hoffman Family Gold
54120: Helicopter ER – Rettung aus der Luft
59585: Die Marine - Unser Leben auf See
60259: Tattoo: Edition Engelhard
60825: Goldrausch: Parkers Neuseeland-Abenteuer
60827: FIFA: Zwischen Machtgier und Korruption
65780: VanTastic! - Coole Camper
65994: Police Interceptors - Auf Verfolgungsjagd

**Comment by Maysi2k** [comment]
For Linuxuser (DMAX-URL from Readme): 

`curl -s "https://de-api.loma-cms.com/feloma/page/sendungen/?environment=dmax&v=2" | jq -r '.blocks[].items[] | "\(.title) \(.attributes.showId)"'`

u can use `grep` as a Filter aswell:

`curl -s "https://de-api.loma-cms.com/feloma/page/sendungen/?environment=dmax&v=2" | jq -r '.blocks[].items[] | "\(.title) \(.attributes.showId)"' | grep -i Moonshine`



---

For Windows 11 User (DMAX-URL from Readme):

`curl "https://de-api.loma-cms.com/feloma/page/sendungen/?environment=dmax&v=2" | ConvertFrom-Json | Select-Object -ExpandProperty blocks | Select-Object -ExpandProperty items | ForEach-Object { "$($_.title) $($_.attributes.showId)" }`


u can use `findstr` as a Filter aswell:

`curl "https://de-api.loma-cms.com/feloma/page/sendungen/?environment=dmax&v=2" | ConvertFrom-Json | Select-Object -ExpandProperty blocks | Select-Object -ExpandProperty items | ForEach-Object { "$($_.title) $($_.attributes.showId)" } | findstr /i Moonshine`

---

For MacOS ❤️ (DMAX-URL from Readme)

`curl -s "https://de-api.loma-cms.com/feloma/page/sendungen/?environment=dmax&v=2" | python3 -c "import sys, json; data = json.load(sys.stdin); print('\n'.join(f\"{item['title']} {item['attributes']['showId']}\" for block in data['blocks'] for item in block['items']))"
`

u can use `grep` as a Filter aswell:


`curl -s "https://de-api.loma-cms.com/feloma/page/sendungen/?environment=dmax&v=2" | python3 -c "import sys, json; data = json.load(sys.stdin); print('\n'.join(f\"{item['title']} {item['attributes']['showId']}\" for block in data['blocks'] for item in block['items']))" | grep -i Moonshine
`
