### ISSUE TITLE
UnicodeEncodeError on download

### ISSUE THREAD

**Issue by Reiner1210** [Brawl345/Get-DMAX-Links#2]
With 
python dmax.py 7163 -s 3

I get an error
Traceback (most recent call last):
  File "dmax.py", line 232, in <module>
    chosen_episode=arguments.episode
  File "dmax.py", line 170, in main
    episode_name=episode.name
UnicodeEncodeError: 'ascii' codec can't encode character u'\xfc' in position 19: ordinal not in range(128)

**Comment by Brawl345** [comment]
Hm, I can't reproduce this on Windows 8.1 x64 with Python 3.8.3. Which version do you have?

**Comment by Maysi2k** [comment]
> With
> python dmax.py 7163 -s 3

how you get the SeriesID?

**Comment by Brawl345** [comment]
@Maysi2k Go to the series you are looking for (e.g. https://dmax.de/sendungen/112-feuerwehr-im-einsatz/ ), press CTRL+U and search for "showid". It's inside the "hyoga-player" tag.

**Comment by Maysi2k** [comment]
Ok Thanks :)

so, the SeriesID from @Reiner1210 is working her, but a other series make also a ASCII-Error.
My Test:

 `python ./dmax.py 13767 -s 1`

>2020-07-02 20:42:03,795 - DMAX - INFO - Getting Authorization token...
>2020-07-02 20:42:04,113 - DMAX - INFO - Getting show data
>Traceback (most recent call last):
>  File "./dmax.py", line 232, in <module>
>    chosen_episode=arguments.episode
>  File "./dmax.py", line 120, in main
>    logger.info("=> {0}".format(show.show.name))
>UnicodeEncodeError: 'ascii' codec can't encode characters in position 26-27: ordinal not in range(128)

Systeminfo: 

- Linux Mint 19.3 Tricia
- Python 2.7.17
- Python3 3.6.9

**Comment by Brawl345** [comment]
It works for me, hm... can you please execute `locale` and give me the output? "LANG" should not be set to C (see https://stackoverflow.com/a/35508945)

**Comment by Maysi2k** [comment]
Here my Output:

> locale

```
LANG=de_DE.UTF-8
LANGUAGE=de_DE
LC_CTYPE="de_DE.UTF-8"
LC_NUMERIC="de_DE.UTF-8"
LC_TIME="de_DE.UTF-8"
LC_COLLATE="de_DE.UTF-8"
LC_MONETARY="de_DE.UTF-8"
LC_MESSAGES="de_DE.UTF-8"
LC_PAPER="de_DE.UTF-8"
LC_NAME="de_DE.UTF-8"
LC_ADDRESS="de_DE.UTF-8"
LC_TELEPHONE="de_DE.UTF-8"
LC_MEASUREMENT="de_DE.UTF-8"
LC_IDENTIFICATION="de_DE.UTF-8"
LC_ALL=
```
> locale -a
```
C
C.UTF-8
de_AT.utf8
de_BE.utf8
de_CH.utf8
de_DE.utf8
de_IT.utf8
de_LI.utf8
de_LU.utf8
en_AG
en_AG.utf8
en_AU.utf8
en_BW.utf8
en_CA.utf8
en_DK.utf8
en_GB.utf8
en_HK.utf8
en_IE.utf8
en_IL
en_IL.utf8
en_IN
en_IN.utf8
en_NG
en_NG.utf8
en_NZ.utf8
en_PH.utf8
en_SG.utf8
en_US.utf8
en_ZA.utf8
en_ZM
en_ZM.utf8
en_ZW.utf8
POSIX
```

**Comment by Brawl345** [comment]
Just tested it and I see the problem - you are using `python` when you should run the script with `python3`, because Linux Mint 19.3 and other distros still have Python 2 installed as `python`. Also make sure to install python3-pip and run `pip3 install -U -r requirements.txt` instead of the normal pip (which uses Python 2).
