### ISSUE TITLE
Not all links working

### ISSUE THREAD

**Issue by jumbi77** [Brawl345/Get-DMAX-Links#21]
Just tried it with showid 60825 fo e.g. Script nicely output all 10 eposides in csv. I tried the generated urls with yt-dlp and youtube-dl and found, that the url is essential if it works or not:

- Links containing `akamaized.net/.../playlist.m3u8` works great
- Links containing `akamaized.net/.../hls_fairPlay_ts/.../master.m3u8` doesnt work (seams drm protected, see output below).

Is there any workaround?
Thanks

Sample output of second url:
```
[generic] master: Downloading webpage
WARNING: [generic] Falling back on generic information extractor.
[generic] master: Downloading m3u8 information
[info] master: Downloading 1 format(s): 9301+audio-aacl-125-English
[hlsnative] Downloading m3u8 manifest
ERROR: This video is DRM protected; Try selecting another format with --format or add --check-formats to automatically fallback to the next best format
```

**Comment by Brawl345** [comment]
Interesting, didn't know that DMAX has shows with DRM. It's Apple's FairPlay DRM. This is nothing I can fix, sorry.

<img width="993" alt="image" src="https://user-images.githubusercontent.com/5049892/218198427-cf5c5451-6abe-4dde-b020-f3b1dbb2ea25.png">

**Comment by Maysi2k** [comment]
Maybe [this](https://github.com/yt-dlp/yt-dlp/) (youtube-dl fork with benefits)  will help, i have't use this, cause a have no Case for this :)

**Comment by Brawl345** [comment]
This project already generates yt-dlp commands. It also can't download DRM'd content sadly.

**Comment by Maysi2k** [comment]
Ok, that's sad.
But cool, that you also use `yt-dlp` - i don't know that :)

I was thinking that project has only `youtube-dl` support and with a quick GoogleSeach yesterday i found this `yt-dlp` with `--allow-u` parameter. But i not try it out.

So finally as a workaroud -> Screenrecording with OBS... :'D :(

**Comment by Brawl345** [comment]
FYI: Updated the program and it uses an endpoint without DRM (well it's one parameter...). https://github.com/Brawl345/Get-DMAX-Links/releases/tag/2024-06-21
