### ISSUE TITLE
dmax - got HTTP status code 500, get a xlsx without links

### ISSUE THREAD

**Issue by Project-Kodi** [Brawl345/Get-DMAX-Links#24]
2024/06/21 16:02:24 got HTTP status code 500
2024/06/21 16:02:24 got HTTP status code 500
2024/06/21 16:02:24 got HTTP status code 500
2024/06/21 16:02:24 got HTTP status code 500
2024/06/21 16:02:24 Couldn't get episode
2024/06/21 16:02:24 Getting link 21 of 22: Tauchgang im Höhlensystem
2024/06/21 16:02:24 got HTTP status code 500
2024/06/21 16:02:24 got HTTP status code 500
2024/06/21 16:02:24 got HTTP status code 500
2024/06/21 16:02:25 got HTTP status code 500
2024/06/21 16:02:25 got HTTP status code 500
2024/06/21 16:02:25 got HTTP status code 500

dmax

get-dmax-links-windows-amd64.exe 18662

**Comment by Brawl345** [comment]
Thanks for the report.

Seems like the data to get the video URL changed. The playback info URL is now `https://eu1-prod.disco-api.com/playback/v3/videoPlaybackInfo` and a POST request is needed now with these data:

```json
{
   "deviceInfo":{
      "adBlocker":false,
      "drmSupported":true,
      "hdrCapabilities":[
         "SDR"
      ],
      "hwDecodingCapabilities":[],
      "soundCapabilities":[
         "STEREO"
      ]
   },
   "wisteriaProperties":{},
   "videoId":"6521922"
}
```

Don't know when/if I will fix it. In the meantime I think jDownloader should also work.

**Comment by Brawl345** [comment]
Fixed, was easier than I thought: https://github.com/Brawl345/Get-DMAX-Links/releases/tag/2024-06-21

**Comment by Project-Kodi** [comment]
thx!
