### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by fnordson** [Brawl345/Get-DMAX-Links#8]
```
2020-10-19 21:47:13,055 - DMAX - INFO - Getting Authorization token for dmaxde...
2020-10-19 21:47:13,552 - DMAX - INFO - Getting show data
2020-10-19 21:47:13,849 - DMAX - INFO - => Steel Buddies
2020-10-19 21:47:13,851 - DMAX - INFO - Getting link 1 of 5
Traceback (most recent call last):
  File "dmax.py", line 263, in <module>
    realm=arguments.realm
  File "dmax.py", line 177, in main
    episode_name=episode.name
UnicodeEncodeError: 'ascii' codec can't encode character u'\xfc' in position 8: ordinal not in range(128)
```
Getting this issue since the last Steel Buddies episode with (updated): dmax.py 6023 -s 8 -e 5

**Comment by Brawl345** [comment]
Possible related to #2, did you use Python 3?

**Comment by fnordson** [comment]
No I didn't. 
It worked before though (I had the command on a how-to txt file). 
I followed the guidelines in the other issue, including the pip3 install. However: 
`python3 dmax.py 6023 -s 8 -e 5`
does nothing at all. 

I did remove all python installations (had 2 older versions there too) and installed one anew. 
Nothing happens. 

I'm on W10 running this in PS with Python3.9 installed.

**Comment by Brawl345** [comment]
I can't reproduce this on Windows 8.1 with Python 3.9. What do you mean with "does nothing at all"? Can you also give me the output of `python3 -V` please?

**Comment by fnordson** [comment]
![py](https://user-images.githubusercontent.com/5624605/96926901-81402480-14b6-11eb-878c-b44d11f0eb65.jpg)
 
This kind of "nothing"... :/

Thanks for the episode though!

**Comment by Brawl345** [comment]
Odd. Can you please show the outputs of:
`python -V`
`where python`
`where python3`

Seems like Python 3 is not in your %PATH% and Python points to an older Python version.

**Comment by fnordson** [comment]
![ps](https://user-images.githubusercontent.com/5624605/96927212-04fa1100-14b7-11eb-9977-2d9977d186dd.jpg)

**Comment by Brawl345** [comment]
And running with just `python` gives the above error? From where did you install Python? From python.org or is it the Linux Subsystem? Also try through the CMD (even if it shouldn't matter). Odd how where doesn't list anything o0

**Comment by fnordson** [comment]
![ps2](https://user-images.githubusercontent.com/5624605/96927681-b6994200-14b7-11eb-8f0e-4019fc33ea68.jpg)

**Comment by Brawl345** [comment]
`pip install -r requirements.txt`
installs the requirements you need

**Comment by fnordson** [comment]
Yes!  
That worked. 
Now I understand that those got lost probably when I uninstalled above but I don't understand why it stopped working when I posted originally...

Well nevermind. Thank you!!

FYI: it works in PS too.
